### ISSUE TITLE
LPUSH with array

### ISSUE THREAD

**Issue by tp** [NodeRedis/node_redis#422]
When supplying an array as second parameter to `lpush` node-redis creates a list but concatenates the single values by `, ` and saves them all as one element.

Is there any convenience method to push/append an array of strings to a list?

**Comment by BridgeAR** [comment]
This is fixed since v.2.0

**Comment by lucaswxp** [comment]
I'm in version 2.6.3 and this is still an issue: ERR wrong number of arguments for 'lpush' command

I tried

                redis.lpush('queue[reducao_tests]', args) // 1

                args.unshift('queue[reducao_tests]') // 2
                redis.lpush(args)

                redis.apply(redis, args) // 3

                args.unshift('queue[reducao_tests]') // 4
                redis.send_command('lpush', args)

Args is an array. All of them gives the same error.
